baseURL: https://ewigl.github.io/notes/
title: Licht's Notes
defaultContentLanguage: zh
theme: PaperMod
pagination:
  # disableAliases: false
  pagerSize: 8
  # path: page

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    # - RSS
    - JSON

params:
  author: Licht

  cover:
    # hidden: true # hide everywhere but not in structured data
    # hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  ShowReadingTime: false
  displayFullLangName: true
  # hideSummary: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowPageNums: true
  ShowToc: true

  disableSpecial1stPost: true

  hideFooter: true

  assets:
    favicon: ./favicon.ico

  label:
    text: Licht
    icon: ./images/logo.png
    iconHeight: 32

  homeInfoParams:
    Title: Licht's Notes
    Content: ğŸ‘‹ Welcome!

  socialIcons:
    - name: Github
      url: https://github.com/ewigl

languages:
  zh:
    languageCode: zh
    languageName: ä¸­æ–‡
    weight: 1
    taxonomies:
      tag: tags
    menu:
      main:
        - name: æœç´¢ ğŸ”
          url: search/
          weight: 10
        - name: å½’æ¡£ ğŸ“š
          url: archives/
          weight: 20
        - name: æ ‡ç­¾ ğŸ”–
          url: tags/
          weight: 30
        - name: åº”ç”¨ ğŸ“
          url: apps/
          weight: 40
        # - name: ç•ªå‰§ ğŸ“º
        #   url: anime/
        #   weight: 50
        # - name: æœŸæœ› ğŸŒŸ
        #   url: expectation/
        # weight: 60
        - name: å…³äº â™
          url: about/
          weight: 70

  en:
    languageCode: en
    languageName: English
    weight: 2
    taxonomies:
      tag: tags
    menu:
      main:
        - name: Search ğŸ”
          url: search/
          weight: 10
        - name: Archives ğŸ“š
          url: archives/
          weight: 20
        - name: Tags ğŸ”–
          url: tags/
          weight: 30
        - name: Apps ğŸ“
          url: apps/
          weight: 40
        - name: About â™
          url: about/
          weight: 60
